apiVersion: v1
kind: Secret
metadata:
  namespace: n8n
  name: n8n-secret
type: Opaque
stringData:
  WEBHOOK_URL: https://n8n.baruzotech.com
  GENERIC_TIMEZONE: Asia/Kolkata
  N8N_EDITOR_BASE_URL: https://n8n.baruzotech.com